import { BinaryWriter, sortDTA, type DTAFile } from '../lib'

/**
 * A class that holds information of all Ruggy Customs.
 */
export class RuggyCustoms {
  /**
   * An array with all songs released by Ruggy.
   */
  static readonly songs: DTAFile[] = [
    {
      id: '7748paintwar',
      name: 'Paint War',
      artist: 'Dream Avenue',
      master: true,
      song_id: 1774800001,
      songname: '7748paintwar',
      tracks_count: [2, 2, 2, 0, 2, 2],
      vocal_parts: 0,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [42914, 72914],
      song_length: 119205,
      rank_drum: 151,
      rank_guitar: 176,
      rank_bass: 1,
      rank_keys: 211,
      rank_real_keys: 211,
      rank_real_guitar: 208,
      rank_real_bass: 1,
      rank_band: 215,
      genre: 'popdanceelectronic',
      sub_genre: 'subgenre_chiptune',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Our Shared Universes',
      album_track_number: 4,
      year_released: 2018,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 9,
      song_tonality: 0,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: false,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
        sub_genre: 'subgenre_chiptune',
      },
    },
    {
      id: '7748southparktheme',
      name: 'South Park Theme',
      artist: 'Primus',
      master: true,
      song_id: 1774800002,
      songname: '7748southparktheme',
      tracks_count: [2, 1, 1, 1, 0, 2],
      vocal_parts: 3,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [4864, 34864],
      song_length: 36318,
      rank_drum: 178,
      rank_guitar: 267,
      rank_bass: 181,
      rank_vocals: 1,
      rank_real_guitar: 325,
      rank_real_bass: 208,
      rank_band: 243,
      genre: 'alternative',
      sub_genre: 'subgenre_alternative',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Chef Aid: The South Park Album',
      album_track_number: 1,
      year_released: 1998,
      rating: 3,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 3,
      song_tonality: 1,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: false,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: false,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748hideandseek',
      name: 'Hide and Seek',
      artist: 'Imogen Heap',
      master: true,
      song_id: 1774800003,
      songname: '7748hideandseek',
      tracks_count: [0, 0, 0, 1, 0, 2],
      vocal_parts: 2,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [142990, 172990],
      song_length: 272649,
      rank_vocals: 279,
      rank_band: 267,
      genre: 'popdanceelectronic',
      sub_genre: 'subgenre_other',
      vocal_gender: 'female',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Speak for Yourself',
      album_track_number: 5,
      year_released: 2005,
      rating: 2,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 9,
      song_tonality: 0,
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: false,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: false,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748cravoecanela',
      name: 'Cravo e Canela',
      artist: 'Clube da Esquina',
      master: true,
      song_id: 1774800004,
      songname: '7748cravoecanela',
      tracks_count: [2, 1, 1, 1, 1, 2],
      vocal_parts: 2,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [32426, 62426],
      song_length: 145042,
      rank_drum: 178,
      rank_guitar: 267,
      rank_bass: 181,
      rank_vocals: 218,
      rank_keys: 211,
      rank_real_keys: 269,
      rank_band: 243,
      solo: ['keys'],
      genre: 'latin',
      sub_genre: 'subgenre_latin',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Clube da Esquina',
      album_track_number: 6,
      year_released: 1972,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 7,
      song_tonality: 0,
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: false,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: false,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
        genre: 'mpb',
        sub_genre: 'subgenre_mpb',
      },
    },
    {
      id: '7748deadwomb',
      name: 'Dead Womb',
      artist: 'Death From Above 1979',
      master: true,
      song_id: 1774800005,
      songname: '7748deadwomb',
      tracks_count: [2, 2, 0, 1, 0, 2],
      vocal_parts: 2,
      hopo_threshold: 250,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 64,
      preview: [21254, 51254],
      song_length: 109098,
      rank_drum: 448,
      rank_bass: 364,
      rank_vocals: 1,
      rank_real_bass: 384,
      rank_band: 345,
      solo: ['bass', 'vocal_percussion'],
      genre: 'punk',
      sub_genre: 'subgenre_dancepunk',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Heads Up',
      album_track_number: 1,
      year_released: 2002,
      rating: 3,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 0,
      song_tonality: 1,
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: false,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: false,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748minuet',
      name: 'Minuet',
      artist: 'From First to Last',
      master: true,
      song_id: 1774800006,
      songname: '7748minuet',
      tracks_count: [0, 0, 2, 0, 0, 1],
      vocal_parts: 0,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [17303, 47303],
      song_length: 67301,
      rank_guitar: 176,
      rank_real_guitar: 208,
      rank_band: 215,
      genre: 'other',
      sub_genre: 'subgenre_acoustic',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Dear Diary, My Teen Angst Has a Body Count',
      album_track_number: 10,
      year_released: 2004,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 2,
      song_tonality: 1,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: false,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748town',
      name: 'Town',
      artist: 'Nathan Grigg',
      master: true,
      song_id: 1774800008,
      songname: '7748town',
      tracks_count: [4, 1, 2, 0, 2, 2],
      vocal_parts: 0,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [9000, 39000],
      song_length: 83000,
      rank_drum: 242,
      rank_guitar: 333,
      rank_bass: 293,
      rank_keys: 443,
      rank_real_keys: 443,
      rank_real_guitar: 325,
      rank_real_bass: 325,
      rank_band: 292,
      solo: ['guitar', 'keys'],
      genre: 'fusion',
      sub_genre: 'subgenre_fusion',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      year_released: 1998,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 11,
      song_tonality: 0,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748passport',
      name: 'Passport',
      artist: 'George Stone',
      master: true,
      song_id: 1774800011,
      songname: '7748passport',
      tracks_count: [4, 2, 2, 0, 2, 2],
      vocal_parts: 0,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 64,
      preview: [89000, 119000],
      song_length: 132705,
      rank_drum: 178,
      rank_guitar: 176,
      rank_bass: 135,
      rank_keys: 327,
      rank_real_keys: 327,
      rank_real_guitar: 267,
      rank_real_bass: 150,
      rank_band: 215,
      genre: 'fusion',
      sub_genre: 'subgenre_fusion',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      year_released: 1995,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 0,
      song_tonality: 1,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748spacecadet',
      name: '3D Pinball Space Cadet: Level 1',
      artist: 'Matt Ridgeway',
      master: true,
      song_id: 1774800012,
      songname: '7748spacecadet',
      tracks_count: [4, 1, 2, 0, 2, 1],
      vocal_parts: 0,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [25785, 55785],
      song_length: 65454,
      rank_drum: 178,
      rank_guitar: 409,
      rank_bass: 228,
      rank_keys: 443,
      rank_real_keys: 443,
      rank_real_guitar: 442,
      rank_real_bass: 325,
      rank_band: 345,
      genre: 'fusion',
      sub_genre: 'subgenre_fusion',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      year_released: 1995,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 8,
      song_tonality: 1,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748spacecadet2x',
      name: '3D Pinball Space Cadet: Level 1 (2x Bass Pedal)',
      artist: 'Matt Ridgeway',
      master: true,
      song_id: 1774800013,
      songname: '7748spacecadet2x',
      tracks_count: [4, 1, 2, 0, 2, 1],
      vocal_parts: 0,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [25785, 55785],
      song_length: 65454,
      rank_drum: 242,
      rank_guitar: 409,
      rank_bass: 228,
      rank_keys: 443,
      rank_real_keys: 443,
      rank_real_guitar: 442,
      rank_real_bass: 325,
      rank_band: 345,
      genre: 'fusion',
      sub_genre: 'subgenre_fusion',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      year_released: 1995,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 8,
      song_tonality: 1,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: true,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748breakingintocars',
      name: 'Breaking Into Cars',
      artist: 'The Raveonettes',
      master: true,
      song_id: 1774800014,
      songname: '7748breakingintocars',
      tracks_count: [2, 1, 1, 1, 0, 2],
      vocal_parts: 2,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [39500, 69500],
      song_length: 194425,
      rank_drum: 1,
      rank_guitar: 139,
      rank_bass: 135,
      rank_vocals: 132,
      rank_real_guitar: 150,
      rank_real_bass: 150,
      rank_band: 163,
      solo: ['guitar', 'vocal_percussion'],
      genre: 'indierock',
      sub_genre: 'subgenre_indierock',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'In and Out of Control',
      album_track_number: 9,
      year_released: 2009,
      rating: 2,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 1,
      song_tonality: 1,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: false,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748aracaazul',
      name: 'Araçá Azul',
      artist: 'Caetano Veloso',
      master: true,
      song_id: 1774800015,
      songname: '7748aracaazul',
      tracks_count: [0, 0, 1, 1, 0, 2],
      vocal_parts: 1,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [25000, 55000],
      song_length: 89593,
      rank_guitar: 139,
      rank_vocals: 175,
      rank_real_guitar: 1,
      rank_band: 157,
      genre: 'latin',
      sub_genre: 'subgenre_latin',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Araçá Azul',
      album_track_number: 10,
      year_released: 1973,
      rating: 1,
      tuning_offset_cents: 35,
      game_origin: 'ugc_plus',
      encoding: 'utf8',
      vocal_tonic_note: 3,
      song_tonality: 0,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: false,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: false,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
        genre: 'mpb',
        sub_genre: 'subgenre_mpb',
      },
    },
    {
      id: '7748demon',
      name: 'Demon',
      artist: 'Bear In Heaven',
      master: true,
      song_id: 1774800016,
      songname: '7748demon',
      tracks_count: [2, 1, 0, 1, 1, 2],
      vocal_parts: 3,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [31000, 61000],
      song_length: 300000,
      rank_drum: 345,
      rank_bass: 1,
      rank_vocals: 132,
      rank_keys: 443,
      rank_real_keys: 327,
      rank_real_bass: 1,
      rank_band: 243,
      solo: ['vocal_percussion'],
      genre: 'indierock',
      sub_genre: 'subgenre_indierock',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Time Is Over One Day Old',
      album_track_number: 7,
      year_released: 2014,
      rating: 3,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 5,
      song_tonality: 1,
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: false,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748cutmyfingersoff',
      name: 'Cutting My Fingers Off',
      artist: 'Turnover',
      master: true,
      song_id: 1774800017,
      songname: '7748cutmyfingersoff',
      tracks_count: [2, 1, 1, 1, 0, 2],
      vocal_parts: 1,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [47917, 77917],
      song_length: 184968,
      rank_drum: 124,
      rank_guitar: 176,
      rank_bass: 1,
      rank_vocals: 132,
      rank_real_guitar: 208,
      rank_real_bass: 1,
      rank_band: 163,
      solo: ['guitar', 'vocal_percussion'],
      genre: 'indierock',
      sub_genre: 'subgenre_indierock',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Peripheral Vision',
      album_track_number: 1,
      year_released: 2015,
      rating: 2,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 0,
      song_tonality: 0,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: false,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: false,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748thefightisover',
      name: 'The Fight is Over',
      artist: 'The Blasting Company',
      master: true,
      song_id: 1774800018,
      songname: '7748thefightisover',
      tracks_count: [2, 1, 1, 1, 0, 2],
      vocal_parts: 3,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [21991, 51991],
      song_length: 87583,
      rank_drum: 1,
      rank_guitar: 176,
      rank_bass: 1,
      rank_vocals: 132,
      rank_real_guitar: 208,
      rank_real_bass: 1,
      rank_band: 78,
      solo: ['guitar'],
      genre: 'glam',
      sub_genre: 'subgenre_glam',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Over The Garden Wall',
      album_track_number: 25,
      year_released: 2017,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 0,
      song_tonality: 0,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: false,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748anysecondnow',
      name: 'Any Second Now (Voices)',
      artist: 'Depeche Mode',
      master: true,
      song_id: 1774800019,
      songname: '7748anysecondnow',
      tracks_count: [0, 1, 0, 1, 1, 2],
      vocal_parts: 2,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [16628, 46628],
      song_length: 163582,
      rank_bass: 1,
      rank_vocals: 132,
      rank_keys: 327,
      rank_real_keys: 269,
      rank_real_bass: 1,
      rank_band: 163,
      solo: ['keys'],
      genre: 'new_wave',
      sub_genre: 'subgenre_synth',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Speak & Spell',
      album_track_number: 10,
      year_released: 1981,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 7,
      song_tonality: 0,
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: false,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: false,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748congratulations',
      name: 'Congratulations',
      artist: 'MGMT',
      master: true,
      song_id: 1774800020,
      songname: '7748congratulations',
      tracks_count: [2, 1, 1, 1, 1, 2],
      vocal_parts: 1,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [79298, 109298],
      song_length: 236430,
      rank_drum: 1,
      rank_guitar: 176,
      rank_bass: 1,
      rank_vocals: 132,
      rank_keys: 443,
      rank_real_keys: 443,
      rank_real_guitar: 150,
      rank_real_bass: 1,
      rank_band: 163,
      solo: ['vocal_percussion', 'keys'],
      genre: 'rock',
      sub_genre: 'subgenre_psychadelic',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Congratulations',
      album_track_number: 9,
      year_released: 2010,
      rating: 2,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 7,
      song_tonality: 0,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: false,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748lightsinthesky',
      name: 'Lights In the Sky',
      artist: 'Nine Inch Nails',
      master: true,
      song_id: 1774800021,
      songname: '7748lightsinthesky',
      tracks_count: [0, 0, 0, 2, 2, 2],
      vocal_parts: 1,
      song_scroll_speed: 2000,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 16,
      preview: [74181, 104181],
      song_length: 222647,
      rank_vocals: 1,
      rank_keys: 1,
      rank_real_keys: 153,
      rank_band: 1,
      genre: 'rock',
      sub_genre: 'subgenre_rock',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'The Slip',
      album_track_number: 7,
      year_released: 2008,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 5,
      song_tonality: 1,
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748mothernature',
      name: 'Mother Nature',
      artist: 'Dream Avenue',
      master: true,
      song_id: 1774800022,
      songname: '7748mothernature',
      tracks_count: [2, 2, 2, 0, 2, 2],
      vocal_parts: 0,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [28413, 58413],
      song_length: 85239,
      rank_drum: 151,
      rank_guitar: 139,
      rank_bass: 1,
      rank_keys: 385,
      rank_real_keys: 385,
      rank_real_guitar: 150,
      rank_real_bass: 150,
      rank_band: 215,
      genre: 'popdanceelectronic',
      sub_genre: 'subgenre_chiptune',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Our Shared Universes',
      album_track_number: 1,
      year_released: 2018,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 4,
      song_tonality: 0,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
        sub_genre: 'subgenre_chiptune',
      },
    },
    {
      id: '7748mindmischief',
      name: 'Mind Mischief',
      artist: 'Tame Impala',
      master: true,
      song_id: 1774800023,
      songname: '7748mindmischief',
      tracks_count: [2, 1, 1, 1, 1, 2],
      vocal_parts: 3,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [26929, 56929],
      song_length: 276114,
      rank_drum: 151,
      rank_guitar: 176,
      rank_bass: 181,
      rank_vocals: 175,
      rank_keys: 1,
      rank_real_keys: 153,
      rank_real_guitar: 208,
      rank_real_bass: 208,
      rank_band: 215,
      solo: ['guitar'],
      genre: 'rock',
      sub_genre: 'subgenre_psychadelic',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Lonerism',
      album_track_number: 4,
      year_released: 2012,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 6,
      song_tonality: 0,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: false,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748theradiant',
      name: 'The Radiant (Chart-A-Thon 2019 Mix)',
      artist: 'Dream Avenue',
      master: true,
      song_id: 1774800024,
      songname: '7748theradiant',
      tracks_count: [2, 2, 2, 0, 2, 2],
      vocal_parts: 0,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 64,
      preview: [14667, 44667],
      song_length: 249333,
      rank_drum: 242,
      rank_guitar: 221,
      rank_bass: 293,
      rank_keys: 385,
      rank_real_keys: 385,
      rank_real_guitar: 325,
      rank_real_bass: 325,
      rank_band: 292,
      genre: 'popdanceelectronic',
      sub_genre: 'subgenre_chiptune',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Moonstone',
      album_track_number: 3,
      year_released: 2014,
      year_recorded: 2019,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 0,
      song_tonality: 0,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
        sub_genre: 'subgenre_chiptune',
      },
    },
    {
      id: '7748whydidntyoustopme',
      name: "Why Didn't You Stop Me?",
      artist: 'Mitski',
      master: true,
      song_id: 1774800025,
      songname: '7748whydidntyoustopme',
      tracks_count: [2, 1, 1, 1, 1, 2],
      vocal_parts: 1,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [22000, 52000],
      song_length: 144000,
      rank_drum: 178,
      rank_guitar: 176,
      rank_bass: 228,
      rank_vocals: 132,
      rank_keys: 153,
      rank_real_keys: 153,
      rank_real_guitar: 208,
      rank_real_bass: 325,
      rank_band: 163,
      solo: ['guitar'],
      genre: 'indierock',
      sub_genre: 'subgenre_indierock',
      vocal_gender: 'female',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Be the Cowboy',
      album_track_number: 2,
      year_released: 2018,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 4,
      song_tonality: 0,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: false,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748thespaceinbetween',
      name: 'The Space in Between',
      artist: 'How to Destroy Angels',
      master: true,
      song_id: 1774800026,
      songname: '7748thespaceinbetween',
      tracks_count: [2, 2, 2, 2, 0, 2],
      vocal_parts: 3,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 16,
      preview: [90811, 120811],
      song_length: 223784,
      rank_drum: 151,
      rank_guitar: 267,
      rank_bass: 1,
      rank_vocals: 175,
      rank_band: 215,
      genre: 'rock',
      sub_genre: 'subgenre_rock',
      vocal_gender: 'female',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'How to Destroy Angels',
      album_track_number: 1,
      year_released: 2010,
      rating: 2,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 7,
      song_tonality: 1,
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748sanguelatino',
      name: 'Sangue Latino',
      artist: 'Secos & Molhados',
      master: true,
      song_id: 1774800027,
      songname: '7748sanguelatino',
      tracks_count: [2, 2, 2, 2, 0, 2],
      vocal_parts: 1,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [55604, 85604],
      song_length: 135401,
      rank_drum: 1,
      rank_guitar: 176,
      rank_bass: 135,
      rank_vocals: 175,
      rank_band: 163,
      genre: 'glam',
      sub_genre: 'subgenre_glam',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Secos & Molhados',
      album_track_number: 1,
      year_released: 1973,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 2,
      song_tonality: 0,
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748robotsinthegarden',
      name: 'Robots in the Garden',
      artist: 'Autolux',
      master: true,
      song_id: 1774800028,
      songname: '7748robotsinthegarden',
      tracks_count: [2, 1, 1, 1, 0, 2],
      vocal_parts: 1,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [55665, 85665],
      song_length: 135401,
      rank_drum: 178,
      rank_guitar: 176,
      rank_bass: 135,
      rank_vocals: 132,
      rank_band: 215,
      solo: ['vocal_percussion'],
      genre: 'rock',
      sub_genre: 'subgenre_rock',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Future Perfect',
      album_track_number: 7,
      year_released: 2004,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 3,
      song_tonality: 1,
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: false,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748ponytail',
      name: 'Ponytail',
      artist: 'Panda Bear',
      master: true,
      song_id: 1774800029,
      songname: '7748ponytail',
      tracks_count: [2, 1, 1, 1, 0, 2],
      vocal_parts: 2,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [14524, 44524],
      song_length: 130025,
      rank_drum: 1,
      rank_guitar: 139,
      rank_bass: 1,
      rank_vocals: 132,
      rank_real_guitar: 150,
      rank_real_bass: 1,
      rank_band: 68,
      genre: 'indierock',
      sub_genre: 'subgenre_indierock',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Person Pitch',
      album_track_number: 7,
      year_released: 2007,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 9,
      song_tonality: 0,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: false,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748beinfriends',
      name: "Bein' Friends",
      artist: 'Keiichi Suzuki & Hirokazu Tanaka',
      master: true,
      song_id: 1774800030,
      songname: '7748beinfriends',
      tracks_count: [4, 1, 1, 0, 1, 1],
      pans: [0, 0, -1, 1, 0, -0.2, 0.2, 0],
      vols: [0, 0, 0, 0, 0, 0, 0, 0],
      vocal_parts: 0,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [3734, 33734],
      song_length: 102679,
      rank_drum: 178,
      rank_guitar: 221,
      rank_bass: 181,
      rank_keys: 211,
      rank_real_keys: 211,
      rank_real_guitar: 325,
      rank_real_bass: 267,
      rank_band: 243,
      genre: 'popdanceelectronic',
      sub_genre: 'subgenre_chiptune',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'MOTHER (Original Soundtrack)',
      album_track_number: 21,
      year_released: 1989,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 5,
      song_tonality: 0,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: false,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
        sub_genre: 'subgenre_chiptune',
      },
    },
    {
      id: '7748hippiebattle',
      name: 'Battle Theme 2 (Hippie Battle)',
      artist: 'Keiichi Suzuki & Hirokazu Tanaka',
      master: true,
      song_id: 1774800031,
      songname: '7748hippiebattle',
      tracks_count: [4, 1, 1, 0, 0, 2],
      vocal_parts: 0,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit03_bank.milo',
      anim_tempo: 64,
      preview: [36000, 66000],
      song_length: 71333,
      rank_drum: 151,
      rank_guitar: 221,
      rank_bass: 228,
      rank_real_guitar: 267,
      rank_real_bass: 267,
      rank_band: 215,
      genre: 'popdanceelectronic',
      sub_genre: 'subgenre_chiptune',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'MOTHER (Original Soundtrack)',
      album_track_number: 7,
      year_released: 1989,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 9,
      song_tonality: 0,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: false,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
        sub_genre: 'subgenre_chiptune',
      },
    },
    {
      id: '7748patins',
      name: 'Patins',
      artist: 'CSS',
      master: true,
      song_id: 1774800032,
      songname: '7748patins',
      tracks_count: [2, 1, 1, 1, 0, 2],
      vocal_parts: 2,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [44569, 74569],
      song_length: 135401,
      rank_drum: 124,
      rank_guitar: 221,
      rank_bass: 1,
      rank_vocals: 132,
      rank_real_guitar: 208,
      rank_real_bass: 1,
      rank_band: 163,
      solo: ['vocal_percussion'],
      genre: 'indierock',
      sub_genre: 'subgenre_indierock',
      vocal_gender: 'female',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Cansei de Ser Sexy (International Release)',
      album_track_number: 2,
      year_released: 2006,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 7,
      song_tonality: 0,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: false,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748motherearth',
      name: 'Mother Earth',
      artist: 'Keiichi Suzuki & Hirokazu Tanaka',
      master: true,
      song_id: 1774800033,
      songname: '7748motherearth',
      tracks_count: [2, 1, 1, 0, 1, 2],
      pans: [-1, 1, 0, -0.2, 0.2, -1, 1],
      vocal_parts: 0,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 16,
      preview: [18668, 48668],
      song_length: 119477,
      rank_drum: 1,
      rank_guitar: 176,
      rank_bass: 135,
      rank_keys: 1,
      rank_real_keys: 1,
      rank_real_guitar: 208,
      rank_real_bass: 150,
      rank_band: 78,
      genre: 'popdanceelectronic',
      sub_genre: 'subgenre_chiptune',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'MOTHER (Original Soundtrack)',
      album_track_number: 1,
      year_released: 1989,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 7,
      song_tonality: 0,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: false,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
        sub_genre: 'subgenre_chiptune',
      },
    },
    {
      id: '7748pollyanna',
      name: 'Pollyanna (I Believe in You)',
      artist: 'Keiichi Suzuki & Hirokazu Tanaka',
      master: true,
      song_id: 1774800034,
      songname: '7748pollyanna',
      tracks_count: [4, 1, 1, 0, 1, 1],
      pans: [0, 0, -1, 1, 0, -0.2, 0.2, 0],
      vocal_parts: 0,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit03_bank.milo',
      anim_tempo: 32,
      preview: [4267, 34267],
      song_length: 121610,
      rank_drum: 124,
      rank_guitar: 221,
      rank_bass: 181,
      rank_keys: 211,
      rank_real_keys: 211,
      rank_real_guitar: 267,
      rank_real_bass: 150,
      rank_band: 215,
      genre: 'popdanceelectronic',
      sub_genre: 'subgenre_chiptune',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'MOTHER (Original Soundtrack)',
      album_track_number: 4,
      year_released: 1989,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 2,
      song_tonality: 0,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [-2, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: false,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
        sub_genre: 'subgenre_chiptune',
      },
    },
    {
      id: '7748twinkle',
      name: 'Twinkle Elementary School',
      artist: 'Keiichi Suzuki & Hirokazu Tanaka',
      master: true,
      song_id: 1774800035,
      songname: '7748twinkle',
      tracks_count: [4, 1, 1, 0, 1, 1],
      pans: [0, 0, -1, 1, 0, 0.2, -0.2, 0],
      vocal_parts: 0,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [3200, 33200],
      song_length: 126408,
      rank_drum: 124,
      rank_guitar: 139,
      rank_bass: 181,
      rank_keys: 269,
      rank_real_keys: 269,
      rank_real_guitar: 150,
      rank_real_bass: 208,
      rank_band: 243,
      genre: 'popdanceelectronic',
      sub_genre: 'subgenre_chiptune',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'MOTHER (Original Soundtrack)',
      album_track_number: 19,
      year_released: 1989,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 9,
      song_tonality: 0,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: false,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
        sub_genre: 'subgenre_chiptune',
      },
    },
    {
      id: '7748tetodevidro',
      name: 'Teto de Vidro',
      artist: 'Pitty',
      master: true,
      song_id: 1774800036,
      songname: '7748tetodevidro',
      tracks_count: [2, 2, 2, 2, 0, 2],
      vocal_parts: 1,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [39735, 69735],
      song_length: 215036,
      rank_drum: 151,
      rank_guitar: 176,
      rank_bass: 135,
      rank_vocals: 175,
      rank_band: 215,
      genre: 'rock',
      sub_genre: 'subgenre_rock',
      vocal_gender: 'female',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Admirável Chip Novo',
      album_track_number: 1,
      year_released: 2005,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'utf8',
      vocal_tonic_note: 1,
      song_tonality: 1,
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: false,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748lennastheme',
      name: "Lenna's Theme",
      artist: 'Nobuo Uematsu',
      master: true,
      song_id: 1774800037,
      songname: '7748lennastheme',
      tracks_count: [0, 2, 2, 0, 2, 2],
      vocal_parts: 0,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 16,
      preview: [34868, 64868],
      song_length: 116955,
      rank_guitar: 139,
      rank_bass: 1,
      rank_keys: 153,
      rank_real_keys: 153,
      rank_real_guitar: 150,
      rank_real_bass: 1,
      rank_band: 163,
      genre: 'classical',
      sub_genre: 'subgenre_classical',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Final Fantasy V (Original Soundtrack)',
      album_track_number: 5,
      year_released: 1992,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 0,
      song_tonality: 0,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: false,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748fateinhaze',
      name: 'Fate in Haze',
      artist: 'Nobuo Uematsu',
      master: true,
      song_id: 1774800038,
      songname: '7748fateinhaze',
      tracks_count: [2, 2, 2, 0, 2, 2],
      vocal_parts: 0,
      hopo_threshold: 90,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 16,
      preview: [12664, 42664],
      song_length: 147797,
      rank_drum: 1,
      rank_guitar: 139,
      rank_bass: 1,
      rank_keys: 211,
      rank_real_keys: 211,
      rank_real_guitar: 150,
      rank_real_bass: 1,
      rank_band: 88,
      genre: 'classical',
      sub_genre: 'subgenre_classical',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Final Fantasy V (Original Soundtrack)',
      album_track_number: 6,
      year_released: 1992,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 1,
      song_tonality: 0,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748royalpalace',
      name: 'Royal Palace',
      artist: 'Nobuo Uematsu',
      master: true,
      song_id: 1774800039,
      songname: '7748royalpalace',
      tracks_count: [5, 2, 0, 0, 2, 2],
      vocal_parts: 0,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [10536, 40536],
      song_length: 95032,
      rank_drum: 124,
      rank_bass: 1,
      rank_keys: 327,
      rank_real_keys: 327,
      rank_real_bass: 1,
      rank_band: 215,
      genre: 'classical',
      sub_genre: 'subgenre_classical',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Final Fantasy V (Original Soundtrack)',
      album_track_number: 21,
      year_released: 1992,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 6,
      song_tonality: 0,
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748magicant',
      name: 'Magicant',
      artist: 'Keiichi Suzuki & Hirokazu Tanaka',
      master: true,
      song_id: 1774800040,
      songname: '7748magicant',
      tracks_count: [4, 1, 0, 0, 1, 1],
      vocal_parts: 0,
      hopo_threshold: 90,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 16,
      preview: [12664, 42664],
      song_length: 147797,
      rank_drum: 1,
      rank_bass: 135,
      rank_keys: 1,
      rank_real_keys: 1,
      rank_real_bass: 325,
      rank_band: 46,
      genre: 'popdanceelectronic',
      sub_genre: 'subgenre_chiptune',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'MOTHER (Original Soundtrack)',
      album_track_number: 17,
      year_released: 1989,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 0,
      song_tonality: 0,
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
        sub_genre: 'subgenre_chiptune',
      },
    },
    {
      id: '7748smb2playersel',
      name: 'Super Mario Bros. 2: Player Select',
      artist: 'Koji Kondo',
      master: true,
      song_id: 1774800041,
      songname: '7748smb2playersel',
      tracks_count: [2, 1, 1, 0, 1, 2],
      pans: [-1, 1, 0, -0.2, 0.2, -1, 1],
      vocal_parts: 0,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [6400, 36400],
      song_length: 147797,
      rank_drum: 151,
      rank_guitar: 221,
      rank_bass: 135,
      rank_keys: 385,
      rank_real_keys: 385,
      rank_real_guitar: 267,
      rank_real_bass: 150,
      rank_band: 243,
      genre: 'popdanceelectronic',
      sub_genre: 'subgenre_chiptune',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Super Mario Bros 2 (Original Soundtrack)',
      album_track_number: 2,
      year_released: 1988,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 0,
      song_tonality: 0,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
        sub_genre: 'subgenre_chiptune',
      },
    },
    {
      id: '7748itstimetojump',
      name: "It's Time to Jump",
      artist: 'Dream Avenue',
      master: true,
      song_id: 1774800042,
      songname: '7748itstimetojump',
      tracks_count: [2, 2, 2, 0, 2, 2],
      vocal_parts: 0,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 64,
      preview: [98900, 128900],
      song_length: 286408,
      rank_drum: 448,
      rank_guitar: 221,
      rank_bass: 135,
      rank_keys: 443,
      rank_real_keys: 443,
      rank_real_guitar: 267,
      rank_real_bass: 150,
      rank_band: 292,
      genre: 'popdanceelectronic',
      sub_genre: 'subgenre_chiptune',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Moonstone',
      album_track_number: 11,
      year_released: 2014,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 3,
      song_tonality: 0,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: false,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
        sub_genre: 'subgenre_chiptune',
      },
    },
    {
      id: '7748wisdomoftheworld',
      name: 'Wisdom of the World',
      artist: 'Keiichi Suzuki & Hirokazu Tanaka',
      master: true,
      song_id: 1774800043,
      songname: '7748wisdomoftheworld',
      tracks_count: [0, 1, 1, 0, 1, 1],
      vocal_parts: 0,
      hopo_threshold: 90,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 16,
      preview: [5868, 35868],
      song_length: 173105,
      rank_guitar: 139,
      rank_bass: 1,
      rank_keys: 1,
      rank_real_keys: 1,
      rank_real_guitar: 150,
      rank_real_bass: 1,
      rank_band: 47,
      genre: 'popdanceelectronic',
      sub_genre: 'subgenre_chiptune',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'MOTHER (Original Soundtrack)',
      album_track_number: 15,
      year_released: 1989,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 0,
      song_tonality: 0,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
        sub_genre: 'subgenre_chiptune',
      },
    },
    {
      id: '7748toweroflahja',
      name: 'Tower of Lahja',
      artist: 'Ryuichi Nitta & Mayuko Okamura',
      master: true,
      song_id: 1774800044,
      songname: '7748toweroflahja',
      tracks_count: [3, 1, 1, 0, 1, 1],
      vocal_parts: 0,
      hopo_threshold: 250,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit03_bank.milo',
      anim_tempo: 64,
      preview: [6667, 36667],
      song_length: 223784,
      rank_drum: 345,
      rank_guitar: 176,
      rank_bass: 1,
      rank_keys: 269,
      rank_real_keys: 269,
      rank_real_guitar: 267,
      rank_real_bass: 1,
      rank_band: 243,
      genre: 'popdanceelectronic',
      sub_genre: 'subgenre_chiptune',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Ninja Gaiden II: The Dark Sword of Chaos (Original Soundtrack)',
      album_track_number: 12,
      year_released: 1990,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 9,
      song_tonality: 1,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
        sub_genre: 'subgenre_chiptune',
      },
    },
    {
      id: '7748myhome',
      name: 'My Home',
      artist: 'Keiichi Suzuki & Hirokazu Tanaka',
      master: true,
      song_id: 1774800045,
      songname: '7748myhome',
      tracks_count: [2, 1, 1, 0, 1, 2],
      vocal_parts: 0,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 16,
      preview: [3600, 33600],
      song_length: 122409,
      rank_drum: 1,
      rank_guitar: 1,
      rank_bass: 1,
      rank_keys: 1,
      rank_real_keys: 1,
      rank_real_guitar: 1,
      rank_real_bass: 1,
      rank_band: 1,
      genre: 'popdanceelectronic',
      sub_genre: 'subgenre_chiptune',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'MOTHER (Original Soundtrack)',
      album_track_number: 2,
      year_released: 1989,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 8,
      song_tonality: 0,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
        sub_genre: 'subgenre_chiptune',
      },
    },
    {
      id: '7748allthatineeded',
      name: 'All That I Needed (Was You)',
      artist: 'Keiichi Suzuki & Hirokazu Tanaka',
      master: true,
      song_id: 1774800046,
      songname: '7748allthatineeded',
      tracks_count: [4, 1, 1, 0, 1, 1],
      vocal_parts: 0,
      hopo_threshold: 250,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [3200, 33200],
      song_length: 97610,
      rank_drum: 151,
      rank_guitar: 221,
      rank_bass: 135,
      rank_keys: 211,
      rank_real_keys: 211,
      rank_real_guitar: 267,
      rank_real_bass: 150,
      rank_band: 215,
      genre: 'popdanceelectronic',
      sub_genre: 'subgenre_chiptune',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'MOTHER (Original Soundtrack)',
      album_track_number: 31,
      year_released: 1989,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 9,
      song_tonality: 0,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: false,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
        sub_genre: 'subgenre_chiptune',
      },
    },
    {
      id: '7748polyesterjammy',
      name: 'Polyester Jammy',
      artist: 'David Rippy & Stephen Rippy',
      master: true,
      song_id: 1774800047,
      songname: '7748polyesterjammy',
      tracks_count: [2, 0, 2, 0, 2, 2],
      vocal_parts: 0,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit03_bank.milo',
      anim_tempo: 32,
      preview: [19200, 49200],
      song_length: 149576,
      rank_drum: 124,
      rank_guitar: 176,
      rank_keys: 211,
      rank_real_keys: 211,
      rank_real_guitar: 1,
      rank_band: 163,
      genre: 'classical',
      sub_genre: 'subgenre_classical',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'Age of Empires: The Rise of Rome (Original Soundtrack)',
      album_track_number: 5,
      year_released: 1998,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 0,
      song_tonality: 1,
      real_guitar_tuning: [0, 0, 0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: false,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748xnfrnfl',
      name: 'xnfrnfl',
      artist: 'marianaa',
      master: true,
      song_id: 1774800048,
      songname: '7748xnfrnfl',
      tracks_count: [2, 1, 1, 1, 0, 2],
      vocal_parts: 2,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [28088, 58088],
      song_length: 147789,
      rank_drum: 1,
      rank_guitar: 176,
      rank_bass: 1,
      rank_vocals: 1,
      rank_band: 45,
      solo: ['vocal_percussion'],
      genre: 'emo',
      sub_genre: 'subgenre_emo',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'sdds rolê lixo',
      album_track_number: 2,
      year_released: 2018,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'utf8',
      vocal_tonic_note: 0,
      song_tonality: 0,
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: false,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: false,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
    {
      id: '7748humoresque',
      name: 'Humoresque of a Little Dog',
      artist: 'Keiichi Suzuki & Hirokazu Tanaka',
      master: true,
      song_id: 1774800049,
      songname: '7748humoresque',
      tracks_count: [4, 1, 0, 0, 1, 1],
      vocal_parts: 0,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 32,
      preview: [3200, 33200],
      song_length: 107214,
      rank_drum: 124,
      rank_bass: 1,
      rank_keys: 269,
      rank_real_keys: 269,
      rank_real_bass: 1,
      rank_band: 163,
      genre: 'popdanceelectronic',
      sub_genre: 'subgenre_chiptune',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'MOTHER (Original Soundtrack)',
      album_track_number: 12,
      year_released: 1989,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 7,
      song_tonality: 0,
      real_bass_tuning: [0, 0, 0, 0],
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: true,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: false,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
        genre: 'chiptune',
        sub_genre: 'subgenre_chiptune',
      },
    },
    {
      id: '7748track9',
      name: '9 (ft. Panda Bear)',
      artist: 'Dean Blunt',
      master: true,
      song_id: 1774800050,
      songname: '7748track9',
      tracks_count: [2, 1, 1, 1, 0, 2],
      vocal_parts: 2,
      song_scroll_speed: 2300,
      bank: 'sfx/tambourine_bank.milo',
      drum_bank: 'sfx/kit01_bank.milo',
      anim_tempo: 16,
      preview: [18388, 48388],
      song_length: 95341,
      rank_drum: 1,
      rank_bass: 1,
      rank_guitar: 139,
      rank_vocals: 132,
      rank_band: 1,
      genre: 'indierock',
      sub_genre: 'subgenre_indierock',
      vocal_gender: 'male',
      format: 10,
      version: 30,
      album_art: true,
      album_name: 'ZUCHI',
      album_track_number: 9,
      year_released: 2020,
      rating: 1,
      game_origin: 'ugc_plus',
      encoding: 'latin1',
      vocal_tonic_note: 7,
      song_tonality: 1,
      author: 'Ruggy',
      languages: ['english'],
      karaoke: false,
      multitrack: false,
      convert: false,
      double_kick: false,
      rhythm_on_keys: false,
      rhythm_on_bass: false,
      cat_ehm: true,
      expert_only: false,
      customsource: {
        game_origin: 'ruggy',
      },
    },
  ]

  /**
   * Returns a list of IDs used on all songs.
   * - - - -
   * @returns {string}
   */
  static getIDList(): string {
    const io = new BinaryWriter()
    const sortedSongs = sortDTA(RuggyCustoms.songs, 'Song ID')

    for (const songs of sortedSongs) {
      io.write(`${String(songs.song_id).slice(-3)} ${songs.name}\n`)
    }

    return io.toBuffer().toString()
  }

  /**
   * Get the parsed song object based on its ID (shortname).
   * - - - -
   * @param {string} id The ID (shortname) of the song.
   * @returns {DTAFile | undefined} Returns the found parsed song object or
   * `undefined` if no song is found.
   */
  static getSongByID(id: string): DTAFile | undefined {
    return RuggyCustoms.songs.find((song) => String(song.id) === String(id))
  }
}
